# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/childprocess/all/childprocess.rbi
#
# childprocess-4.1.0

module ChildProcess
end
class ChildProcess::Error < StandardError
end
class ChildProcess::TimeoutError < ChildProcess::Error
end
class ChildProcess::SubclassResponsibility < ChildProcess::Error
end
class ChildProcess::InvalidEnvironmentVariable < ChildProcess::Error
end
class ChildProcess::LaunchError < ChildProcess::Error
end
class ChildProcess::MissingFFIError < ChildProcess::Error
end
class ChildProcess::MissingPlatformError < ChildProcess::Error
end
class ChildProcess::AbstractProcess
end
class ChildProcess::AbstractIO
end
module ChildProcess::Unix
end
class ChildProcess::Unix::IO < ChildProcess::AbstractIO
end
class ChildProcess::Unix::Process < ChildProcess::AbstractProcess
end
class ChildProcess::Unix::ForkExecProcess < ChildProcess::Unix::Process
end
