# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/io-wait/all/io-wait.rbi
#
# io-wait-0.2.1

class IO
  def nread; end
  def ready?; end
  def wait(*arg0); end
  def wait_readable(*arg0); end
  def wait_writable(*arg0); end
end
